version: "3.8"
services:

# DB
    db-mongo:
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
        volumes:
            - ./db-mongodb/:/docker-entrypoint-initdb.d/entrypoint.js:ro
        # Stop logging
        logging:
            driver: none

    db-sqlserver:
        build:
            context: ./db-sqlserver
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: ${SQLSERVER_ROOT_PASSWORD}
            ACCEPT_EULA: "Y"
        # Stop logging
        logging:
            driver: none

    proxy:
        build: ./node-proxy
        ports:
            - 8000:8000
        volumes:
            - ./node-proxy:/app

# Services
    service-auth:
        build: ./node-service-auth
        depends_on:
            - db-sqlserver
        volumes:
            - ./node-service-auth:/app
        
    service-users:
        build: ./node-service-users
        depends_on:
             - db-sqlserver
             - db-mongo
        volumes:
            - ./node-service-users:/app

    service-orders:
#        scale: 2
        build: ./node-service-orders
        depends_on:
             - db-mongo
        volumes:
            - ./node-service-orders:/app

    service-restaurants:
        build: ./node-service-restaurants
        depends_on:
             - db-mongo
        volumes:
            - ./node-service-restaurants:/app
#    service-test:
#        build: ./node-service
#        depends_on:
#             - db-mongo
#        volumes:
#            - ./node-service:/app
# /!\ Only for production, for test use `npm run serve` on the host inside the ./node-vuejs
#    prod-vuejs:
#        build:
#            context: ./node-vuejs
#        ports:
#            - 8080:8080