version: "3.8"
services:

# DB
#    db-mongo:
#        image: mongo:latest
#        restart: always
#        ports:
#            - 27017:27017
#        environment:
#            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
#            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
#        volumes:
#            - ./db-mongodb/:/docker-entrypoint-initdb.d/entrypoint.js:ro
#        command: mongod --quiet --logpath /dev/null 

    db-sqlserver:
        build:
            context: ./db-sqlserver
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: ${SQLSERVER_ROOT_PASSWORD}
            ACCEPT_EULA: "Y"
        
#    nginx:
#        image: nginx:1.19
#        ports:
#            - 80:80
#        volumes:
#            - "./nginx/templates:/etc/nginx/templates"
#            - "./nginx/env-conf:/etc/nginx/env-conf"
    auth:
        build: ./node-auth
        depends_on:
            - db-sqlserver
        ports:
            - 3000:3000
        volumes:
            - ./node-auth:/app

#    service:
#        build:
#            context: ./node-service
#        ports:
#            - "3000"
#        volumes:
#            - "./node-service"