version: "3.8"
services:

# DB
#    db-mongo:
#        image: mongo:latest
#        restart: always
#        ports:
#            - 27017:27017
#        environment:
#            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
#            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
#        volumes:
#            - ./db-mongodb/:/docker-entrypoint-initdb.d/entrypoint.js:ro
#        command: mongod --quiet --logpath /dev/null 

    db-sqlserver:
        build:
            context: ./db-sqlserver
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: ${SQLSERVER_ROOT_PASSWORD}
            ACCEPT_EULA: "Y"
        
#    proxy:
#        build: ./node-proxy
#        ports:
#            - 3000:3000
#        volumes:
#            - ./node-proxy:/app

# Services
    service-auth:
        build: ./node-service-auth
        depends_on:
            - db-sqlserver
        ports:
            - 3000:3000
        volumes:
            - ./node-service-auth:/app

    service-test:
        build: ./node-service
#        depends_on:
#            - db-mongo
        ports:
            - 8000:3000
        volumes:
            - ./node-service:/app